---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: test-backend
  namespace: test
spec:
  selector:
    matchLabels:
      app: myapp
      tier: backend
  replicas: 2
  minReadySeconds: 5
  progressDeadlineSeconds: 300
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template: 
    metadata:
      labels:
        app: myapp
        tier: backend
    spec:
      containers:
      - name: myappbe
        image: nirmalmarisetty/myk8simage-testbe-080919:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "500Mi"
          requests:
            cpu: "0.2"
            memory: "200Mi"